lab6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web_tdd/', include('web_tdd.urls')),
    path('profile/', include('story10.urls')),
    path('list_book/', include('list_book.urls')),
    path('book_list/', include('story11.urls')),
    path('status/', include('web_tdd.urls')),
    path('', include('web_tdd.urls')),
]

story10/urls.py
from django.urls import include, path
from . import views

app_name = 'story10'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('check_email/', views.check_email, name = 'check_email'),
    path('add_subscriber/', views.add_subscriber, name = 'add_subscriber'),
    path('web_service/', views.web_service, name = 'web_service'),
    path('delete_user/', views.delete_user, name = 'delete_user')
]

web_tdd/urls.py
from django.urls import include, path
from . import views

app_name = 'web_tdd'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('add_status', views.add_status, name = 'add_status'),
    path('delete_all_stat_db', views.delete_all_stat_db, name = 'delete_all_stat_db'),
    path('profiles', views.profile, name = 'profile')
]

web_tdd/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Status(models.Model):
    content = models.TextField(max_length = 300)
    created_date = models.DateTimeField(default = timezone.now)

web_tdd/forms.py
from django import forms

class Status_Form(forms.Form):
    error_msg = {
        'required' : 'This field is required',
    }

    content_attrs = {
        'type' : 'textarea',
        'class' : 'status-form-textarea',
        'placeholder' : 'Write your status...',
        'rows' : '3px'
    }

    content = forms.CharField(
        label = '',
        required = True,
        max_length = 300,
        widget = forms.Textarea(attrs = content_attrs)
    )
    

web_tdd/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
# Create your views here.
def index(request):
    response = {}
    response['status_form'] = Status_Form
    html = 'index.html/'
    all_status = Status.objects.all().order_by('-pk')
    response['status'] = all_status

    return render(request, html, response)

def add_status(request):
    response = {}
    form = Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['content'] = request.POST['content']
        status = Status(content = response['content'])
        status.save()
    
    return HttpResponseRedirect('/')

def delete_all_stat_db(request):
    Status.objects.all().delete()
    return HttpResponseRedirect('/')
    
def profile(request):
    response = {}
    html = 'profile.html'
    return render(request, html, response)

web_tdd/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Karla:700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{%static "css/foundation.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{%static "css/style.css" %}">
    <title>Landing Page</title>
</head>
<body>
    <div class="grid-x">
        <div class="cell medium-2">
            
        </div>
        <div class="cell medium-3">
            <div class="write-content">
                <h1>Hello, apa kabar?</h1>
                <form action="{% url 'web_tdd:add_status' %}" id="form" method="POST">
                    {% csrf_token %}
                    {{ status_form }}
                    <button type="submit" name="submit" class="button expanded">Submit</button>
                </form>
                <a href="{% url 'story10:index' %}"> View my profile </a>
            </div>
        </div>

        <div class="cell medium-5 form-content">
            {% if status %}
            {% for i in status %}
            <div class="status-item">
                <h4><b>{{ i.content }}</b></h4>
                {{ i.created_date.date }}
                {{ i.created_date.time }}
                <br>
            </div>
            {% endfor %}
            <div>
                <a class="button expanded delete-button" href="{% url 'web_tdd:delete_all_stat_db' %}">Delete All</a> 
            </div>
            {% else %}
            <div class="status-item text-center">
                <h4 style="color: #bdc3c7;"><b>Belum ada status</b></h4>
            </div>
            {% endif %}
        </div>
        
        <div class="cell medium-2">
            
        </div>    
    </div>
    
</body>
</html>

web_tdd/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/css?family=Karla:700" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{%static "css/foundation.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{%static "css/style.css" %}">
        <title>Landing Page</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="{%static "js/profile.js" %}"></script>
        <script>
            
        </script>
    </head>
    <body id='body' class="theme-1">
        <div class="loading-page"></div>
        <div class="select-button text-center">
            <button type="button" class="button notch" id="change-theme"> Dark mode </button>
        </div>

        <div class="profile-container grid-x align-middle">
            <div class="cell medium-1">
            </div>
            <div class="cell medium-6" id="showup" style="display:none;">
                <h3><i>Name:</i></h3>
                <h1>Aryo Tinulardhi</h1>
                <h3><i>Gender:</i></h3>
                <h1>Male</h1>
                <h3><i>NPM:</i></h3>
                <h1>1706039515</h1>
            </div> 
            <div class="cell medium-5 text-center">
                <h1>Who Am I?</h1>
                <a><img id="myImage" style="max-height: 50vh;" src="{%static "img/avatar.png" %}" onclick="changeImage()" alt=""></a>
                <h4 id="click-me">Click me!</h4>
            </div>
        </div>
        <div class="profile-container grid-x align-middle">
            <div class="medium-1">

            </div>
            <div class="cell medium-5">
                <h1 class="you-know-me">You<br>Know<br>Me?</h1>
            </div>
            <div class="cell medium-5">
                <button class="accordion">My Activity</button>
                <div class="panel">
                    <p>
                        <ul>
                            <li>Life</li>
                            <li>Code</li>
                            <li>Repeat</li>
                        </ul>
                    </p>
                </div>
                
                <button class="accordion">My Organization Record</button>
                <div class="panel">
                    <p>
                        <ul>
                            <li>Staff Humas - BEM Fasilkom UI</li>
                            <li>Staff Online Marketing - COMPFEST X</li>
                            <li>PIC Public Relation and Publication - OH Fasilkom UI 2018</li>
                        </ul>
                    </p>
                </div>
                
                <button class="accordion">My Achievement</button>
                <div class="panel">
                    <p>
                        <ul>
                            <li>Survive in Fasilkom</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>

       

    </body>
</html>